### ISSUE TITLE
The cls_ids.pickle file for the coco is missing

### ISSUE THREAD

**Issue by KX-Zhang** [sunxm2357/DualCoOp#5]
Dear author, I find the cls_ids.pickle file missing while reproducing the zero-shot experiment on the coco dataset. 
Specifically, I do not find the cls_ids.pickle of coco in the download link (https://drive.google.com/file/d/154dkD7Ok1xxwTZb7hQTAf3FlNCN8Q6KM/view?usp=sharing) that you give. 
Please tell me how to get the cls_ids.pickle or directly give the file.

**Comment by KX-Zhang** [comment]
The author of this work sent the file to me by email, and anyone in need can download the attachment.
[cls_ids.zip](https://github.com/sunxm2357/DualCoOp/files/11310072/cls_ids.zip)

**Comment by sorrowyn** [comment]
> The author of this work sent the file to me by email, and anyone in need can download the attachment. [cls_ids.zip](https://github.com/sunxm2357/DualCoOp/files/11310072/cls_ids.zip)

Thank you.
